const CONTENT = {
  ko: {
    profile: {
      name: "홍길동",
      role: "Frontend Developer",
      intro: "사용자 경험과 제품 임팩트를 연결하는 웹 프론트엔드 개발자입니다.",
    },
    about: {
      body: "문제를 빠르게 실험하고 측정 가능한 결과로 연결하는 데 집중합니다. 팀 협업에서는 명확한 커뮤니케이션과 문서화를 중요하게 생각합니다.",
    },
    experience: [
      {
        org: "ABC Tech",
        role: "프론트엔드 개발자",
        period: "2023.03 - 현재",
        summary: "디자인 시스템을 구축해 신규 화면 개발 시간을 단축하고, 핵심 퍼널 성과를 개선했습니다.",
      },
      {
        org: "Startup XYZ",
        role: "주니어 웹 개발자",
        period: "2021.07 - 2023.02",
        summary: "운영 페이지 성능 최적화와 A/B 테스트를 통해 사용자 전환율을 개선했습니다.",
      },
    ],
    projects: [
      {
        title: "Portfolio Analytics Dashboard",
        summary: "프로젝트 성과 지표를 한눈에 볼 수 있는 대시보드. 로딩 시간을 줄이고 탐색성을 개선했습니다.",
        tech: ["JavaScript", "Chart.js", "CSS"],
        link: "https://github.com/your-id/analytics-dashboard",
        period: "2025",
      },
      {
        title: "Design Token Playground",
        summary: "디자인 토큰 변경 사항을 즉시 시각화해 디자이너-개발자 협업 속도를 높인 도구입니다.",
        tech: ["TypeScript", "Vite", "PostCSS"],
        link: "https://github.com/your-id/design-token-playground",
        period: "2024",
      },
      {
        title: "Team Wiki Portal",
        summary: "사내 위키 문서를 검색/탐색하기 쉽게 정리한 포털로 온보딩 시간을 단축했습니다.",
        tech: ["React", "Node.js", "SQLite"],
        link: "https://github.com/your-id/team-wiki-portal",
        period: "2023",
      },
    ],
    contact: {
      email: "hello@example.com",
      github: "https://github.com/your-id",
      linkedin: "https://www.linkedin.com/in/your-id",
    },
    ui: {
      pageTitle: "홍길동 | 포트폴리오",
      eyebrow: "PORTFOLIO",
      navAbout: "소개",
      navExperience: "이력",
      navProjects: "프로젝트",
      navContact: "연락",
      ctaProjects: "프로젝트 보기",
      ctaContact: "연락하기",
      sectionAbout: "소개",
      sectionExperience: "이력",
      sectionProjects: "프로젝트",
      sectionContact: "연락",
      projectsLead: "문제를 해결한 핵심 결과 중심으로 정리했습니다.",
      contactLead: "아래 채널로 연락 주시면 24시간 내에 회신드리겠습니다.",
      contactEmail: "이메일",
      projectPeriod: "기간",
      projectTech: "기술",
      projectLink: "프로젝트 링크",
      footer: "2026 Hong Gil-dong. Built for GitHub Pages.",
    },
  },
  en: {
    profile: {
      name: "Hong Gil-dong",
      role: "Frontend Developer",
      intro: "I build web products that connect user experience to measurable business impact.",
    },
    about: {
      body: "I focus on fast iteration, measurable outcomes, and reliable collaboration. I value clear communication and practical documentation in teams.",
    },
    experience: [
      {
        org: "ABC Tech",
        role: "Frontend Developer",
        period: "Mar 2023 - Present",
        summary: "Built a design system that reduced delivery time for new screens and improved key funnel metrics.",
      },
      {
        org: "Startup XYZ",
        role: "Junior Web Developer",
        period: "Jul 2021 - Feb 2023",
        summary: "Improved conversion through performance optimization and repeated A/B testing on growth pages.",
      },
    ],
    projects: [
      {
        title: "Portfolio Analytics Dashboard",
        summary: "Dashboard for project KPIs with faster loading and clearer navigation for quick insight.",
        tech: ["JavaScript", "Chart.js", "CSS"],
        link: "https://github.com/your-id/analytics-dashboard",
        period: "2025",
      },
      {
        title: "Design Token Playground",
        summary: "Tool to visualize design token updates instantly, improving designer-developer collaboration speed.",
        tech: ["TypeScript", "Vite", "PostCSS"],
        link: "https://github.com/your-id/design-token-playground",
        period: "2024",
      },
      {
        title: "Team Wiki Portal",
        summary: "Internal wiki portal with better search and navigation that reduced onboarding time.",
        tech: ["React", "Node.js", "SQLite"],
        link: "https://github.com/your-id/team-wiki-portal",
        period: "2023",
      },
    ],
    contact: {
      email: "hello@example.com",
      github: "https://github.com/your-id",
      linkedin: "https://www.linkedin.com/in/your-id",
    },
    ui: {
      pageTitle: "Hong Gil-dong | Portfolio",
      eyebrow: "PORTFOLIO",
      navAbout: "About",
      navExperience: "Experience",
      navProjects: "Projects",
      navContact: "Contact",
      ctaProjects: "View Projects",
      ctaContact: "Get in Touch",
      sectionAbout: "About",
      sectionExperience: "Experience",
      sectionProjects: "Projects",
      sectionContact: "Contact",
      projectsLead: "A selected list focused on outcome and product impact.",
      contactLead: "Feel free to reach out through the channels below.",
      contactEmail: "Email",
      projectPeriod: "Period",
      projectTech: "Tech",
      projectLink: "Project Link",
      footer: "2026 Hong Gil-dong. Built for GitHub Pages.",
    },
  },
};
